import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import RightSideBar from "@/stories/right-sidebar";
import LeftSidebar from "@/stories/left-sidebar";
import Header from "@/stories/header";
import TaskManagementToolbar from "@/stories/task-managment-toolbar";
import { fetchDirectories, userSession } from "@/lib/utils";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const directories = await fetchDirectories();
  // const session = await userSession();
  // const userId = session?.user?.id!;
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <section className="min-h-screen grid grid-cols-1 lg:grid-cols-6">
            <LeftSidebar tabletOrMobile={false}  directories={directories} />

            <main className="lg:col-span-4 px-4 ">
              <Header directories={directories} />
              <TaskManagementToolbar />
              <div>{children}</div>
            </main>

            <RightSideBar />
          </section>
        </ThemeProvider>
      </body>
    </html>
  );
}
